### PR TITLE
lib: Add Pi3 243390 support

### PR DESCRIPTION
**Pull request by acostach**
Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@acostach since merging your other PR there are some merge conflicts now

**Comment by acostach** [comment]
Thanks for letting me know Ryain, I'll update it as soon as flashing works, as there are some issues with the upstream usbboot firmware

**Comment by acostach** [comment]
Would it be possible to update etcher-sdk to the latest version in leviathan @rcooke-warwick ? Updating rpi firmware blobs in node-raspberrypi-usbboot would imply using the latest etcher sdk, currently it's at v2.0.2 in leviathan and upstream is v7.0.0

**Comment by acostach** [comment]
Relies on https://github.com/balena-io-modules/etcher-sdk/pull/227 getting merged first

**Comment by acostach** [comment]
@rcooke-warwick I've updated the PR to bring in etcher-sdk 7.0.1 and fixed the build error, however, with this PR the CM3 does not enter MSD mode and I suspect it might be because of the fixes I did so that the link check could pass.

I have tested the node-raspberrypi-usbboot module included in this and the CM3 and custom RPi are put in MSD mode:

```
testbot/node-raspberrypi-usbboot$ sudo npx ts-node lib/main.ts   -> CM3
Waiting for BCM2835/6/7
device attached 1-2
progress 1-2 0 %
progress 1-2 3 %
progress 1-2 5 %
progress 1-2 8 %
progress 1-2 10 %
progress 1-2 13 %
progress 1-2 15 %
progress 1-2 18 %
progress 1-2 20 %
progress 1-2 23 %
progress 1-2 98 %
progress 1-2 100 %
device 1-2 is ready
device 1-2 detached
^C
~/testbot/node-raspberrypi-usbboot$ sudo npx ts-node lib/main.ts ---> custom RPI with eMMC
Waiting for BCM2835/6/7
device attached 1-2
progress 1-2 0 %
progress 1-2 3 %
progress 1-2 5 %
progress 1-2 8 %
progress 1-2 10 %
progress 1-2 13 %
progress 1-2 15 %
progress 1-2 18 %
progress 1-2 20 %
progress 1-2 23 %
progress 1-2 98 %
progress 1-2 100 %
device 1-2 is ready
device 1-2 detached
^C

```

However it might be that the FINs sequence need some updating.. Can you please check if the FIN sequence needs updating after this etcher-sdk update? Thank you

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@acostach we just merged a fix for the testbot sdk for fin flashing - the problem you were seeing `Waiting for compute module` was an existing problem, probably not related to your change. It was related to the USB hub not responding to uhubctl. 

I would recommend now retrying your tests on this PR, maybe it will work now

**Comment by acostach** [comment]
Ack, thanks Ryan , I'll try again with the new fixes

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@rcooke-warwick friendly reminder about this, if you can give this PR a spin

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
Hi @rcooke-warwick ,did you get the chance to test this on the CM3?

**Comment by acostach** [comment]
Let's close this PR for now and use the newer https://github.com/balena-io-hardware/testbotsdk/pull/36 cc @rcooke-warwick

**Pull request closed without merging**
